version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: rehearsal
      POSTGRES_PASSWORD: planner
      POSTGRES_DB: rehearsal_db
